### ISSUE TITLE
Unable to run docker container

### ISSUE THREAD

**Issue by terbooter** [ivandokov/phockup#136]
Command in terminal:
```
docker run -v /Volumes/HDD/unsorted_photos:/mnt ivandokov/phockup:latest /mnt/Input /mnt/Output
```
Output:
```
Unable to find image 'ivandokov/phockup:latest' locally
latest: Pulling from ivandokov/phockup
a0d0a0d46f8b: Pull complete
ba51967de001: Pull complete
472f8c18fd1c: Pull complete
02e5da7e751e: Pull complete
ee2011448a5d: Pull complete
6b2a1a42626d: Pull complete
Digest: sha256:902c6c6de9da448cadb2f9d2f47ef53e7788f9d40e2f708dbb8e764fa098c9e5
Status: Downloaded newer image for ivandokov/phockup:latest
Traceback (most recent call last):
  File "/usr/local/bin/phockup", line 11, in <module>
    from src.phockup import Phockup
  File "/opt/phockup/src/phockup.py", line 9, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
```

**Comment by paul-green** [comment]
Me too - same issue. Tried on Windows and Ubuntu. Unfortunately on the machine I want to use it on I can't install using apt - it's Synology DSM 7

**Comment by ivandokov** [comment]
This should be resoved by version 1.7.1 that I just tagged. Please let me know if it is not.
