### ISSUE TITLE
TQDM not found

### ISSUE THREAD

**Issue by MMMXXXZZZ** [ivandokov/phockup#159]
Command used: `phockup.py "Input" "Output" --date "YYYY/MM" --move --original-names --timestamp --dry-run --progress`

Console output:
```
Traceback (most recent call last):
  File "C:\Users\USER\Downloads\phockup-latest\phockup.py", line 11, in <module>
    from src.phockup import Phockup
  File "C:\Users\USER\Downloads\phockup-latest\src\phockup.py", line 11, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
```

Latest Python3, Win11

**Comment by anttitelio** [comment]
I have the same issue on Ubuntu 22.04

**Comment by anttitelio** [comment]
Ah, there's been issue #129 already earlier, but it has been closed even though it seems not to got truly solved

**Comment by tugdualenligne** [comment]
Same issue with phockup installed through brew

**Comment by MMMXXXZZZ** [comment]
Again happening on Mac
`phockup Input Output --date "YYYY/MM" --move --original-names --timestamp --dry-run --progress`

Console output:
```
Traceback (most recent call last):
  File "/opt/homebrew/bin/phockup", line 11, in <module>
    from src.phockup import Phockup
  File "/opt/homebrew/Cellar/phockup/1.9.0/src/phockup.py", line 11, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
```

`brew config` console output:
```
HOMEBREW_VERSION: 3.6.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: b8b195cc64a29595797651720ebb2ea09affb682
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6d9adaa4c01a273fa2dea3271b5cbec9e801b7e6
Core tap last commit: 38 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.0 => /Applications/Xcode-beta.app/Contents/Developer/usr/bin/git
Curl: 7.84.0 => /usr/bin/curl
macOS: 13.0-arm64
CLT: 14.1.0.0.1.1662869207
Xcode: 14.1 => /Applications/Xcode-beta.app/Contents/Developer
Rosetta 2: false
```

**Comment by MMMXXXZZZ** [comment]
**Solved on Mac**

Install TQDM module with `pip install tqdm` or `pip3 install tqdm`

**Comment by elplatt** [comment]
Still having this issue on Ubuntu 22.04 LTS even though tqdm is installed:

    elplatt@marvin:~$ pip3 list | grep tqdm
    tqdm                    4.64.1

    elplatt@marvin:~$ python3 -c "from tqdm import tqdm; print(tqdm);"
    <class 'tqdm.std.tqdm'>

    elplatt@marvin:~$ phockup
    Traceback (most recent call last):
      File "/snap/phockup/407/phockup.py", line 11, in <module>
        from src.phockup import Phockup
      File "/snap/phockup/407/src/phockup.py", line 9, in <module>
        from tqdm import tqdm
    ModuleNotFoundError: No module named 'tqdm'

**Comment by Bananas-Are-Yellow** [comment]
Same here.
```
$ sudo snap install phockup
[sudo] password for david:
2024-08-15T15:02:44+01:00 INFO Waiting for automatic snapd restart...
phockup 1.7.1 from Ivan Dokov (dokov) installed
```
When I run, I get an error about missing `tqdm`:
```
$ phockup
Traceback (most recent call last):
  File "/snap/phockup/407/phockup.py", line 11, in <module>
    from src.phockup import Phockup
  File "/snap/phockup/407/src/phockup.py", line 9, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
```
I tried manually installing `tqdm` but that didn't help.
```
$ pip3 install tqdm
Defaulting to user installation because normal site-packages is not writeable
Collecting tqdm
  Downloading tqdm-4.66.5-py3-none-any.whl (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.4/78.4 KB 2.9 MB/s eta 0:00:00
Installing collected packages: tqdm
Successfully installed tqdm-4.66.5
```
Still not found.
