### ISSUE TITLE
Move to samba: [Errno 18] Invalid cross-device link

### ISSUE THREAD

**Issue by mrkeuz** [ivandokov/phockup#90]
Move images to samba share sometimes interrupt with below error. Remote file will be broken after that. Rerun process (with delete remote file) solves issue for that. Faced with issue several times on folder with ~1000 files.

Will be glad to provide some additional info.

Note: Samba share mounted via wired connection to locally server. So connection should be stable. No other issues with share was not observed.

Environment:
phockup - v1.5.11
Ubuntu 20.04.1
Python 3.8.5

Trace:
OSError: [Errno 18] Invalid cross-device link: './IMG_0057.CR2' -> '/media/NAS2/Photo/Grand_Archive/2020/10/14/IMG_0057.CR2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/phockup", line 100, in <module>
    main(sys.argv[1:])
  File "/usr/local/bin/phockup", line 85, in main
    return Phockup(
  File "/opt/phockup/src/phockup.py", line 38, in __init__
    self.walk_directory()
  File "/opt/phockup/src/phockup.py", line 68, in walk_directory
    self.process_file(file)
  File "/opt/phockup/src/phockup.py", line 159, in process_file
    shutil.move(file, target_file)
  File "/usr/lib/python3.8/shutil.py", line 802, in move
    copy_function(src, real_dst)
  File "/usr/lib/python3.8/shutil.py", line 432, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.8/shutil.py", line 273, in copyfile
    return dst
InterruptedError: [Errno 4] Interrupted system call

**Comment by ivandokov** [comment]
The error sounds unusual to happen only for a certain file but not for the rest. I have no idea how to resolve it.

**Comment by ivandokov** [comment]
I'm closing this for now as this is the only reported issue for Samba.
