### ISSUE TITLE
Custom EXIF Date not working

### ISSUE THREAD

**Issue by thueske** [ivandokov/phockup#97]
Hi together,

I would like to sort my photos with the tool. Unfortunately it does not work as described. Does anyone have an idea?

```
phockup -f "FileModifyDate" pics/originals Fotos

pics/originals/F/F0016971-A83E-48AC-B1DC-F4F38C5931F4.jpegTraceback (most recent call last):
  File "/snap/phockup/375/phockup.py", line 176, in <module>
    main()
  File "/snap/phockup/375/phockup.py", line 170, in main
    dry_run=args.dry_run,
  File "/snap/phockup/375/src/phockup.py", line 38, in __init__
    self.walk_directory()
  File "/snap/phockup/375/src/phockup.py", line 68, in walk_directory
    self.process_file(filepath)
  File "/snap/phockup/375/src/phockup.py", line 145, in process_file
    output, target_file_name, target_file_path = self.get_file_name_and_path(filename)
  File "/snap/phockup/375/src/phockup.py", line 187, in get_file_name_and_path
    date = Date(filename).from_exif(exif_data, self.timestamp, self.date_regex, self.date_field)
  File "/snap/phockup/375/src/date.py", line 33, in from_exif
    keys = date_field.split()
TypeError: Required argument 'string' (pos 1) not found
```

```
exiftool -time:all -mimetype -j pics/originals/F/F0016971-A83E-48AC-B1DC-F4F38C5931F4.jpeg

[{
  "SourceFile": "pics/originals/F/F0016971-A83E-48AC-B1DC-F4F38C5931F4.jpeg",
  "FileModifyDate": "2018:04:20 19:39:07+02:00",
  "FileAccessDate": "2021:01:24 21:36:26+01:00",
  "FileInodeChangeDate": "2021:01:24 22:05:17+01:00",
  "ModifyDate": "2018:04:20 19:39:07",
  "DateTimeOriginal": "2018:04:20 19:39:07",
  "CreateDate": "2018:04:20 19:39:07",
  "SubSecTimeOriginal": 820,
  "SubSecTimeDigitized": 820,
  "ProfileDateTime": "2017:07:07 13:22:32",
  "SubSecCreateDate": "2018:04:20 19:39:07.820",
  "SubSecDateTimeOriginal": "2018:04:20 19:39:07.820",
  "MIMEType": "image/jpeg"
}]
```

Thanks 👍🏻

**Comment by Yfksw65** [comment]
Same for me. 

```
Traceback (most recent call last):
  File "/usr/local/bin/phockup", line 176, in <module>
    main()
  File "/usr/local/bin/phockup", line 160, in main
    return Phockup(
  File "/opt/phockup/src/phockup.py", line 38, in __init__
    self.walk_directory()
  File "/opt/phockup/src/phockup.py", line 68, in walk_directory
    self.process_file(filepath)
  File "/opt/phockup/src/phockup.py", line 145, in process_file
    output, target_file_name, target_file_path = self.get_file_name_and_path(filename)
  File "/opt/phockup/src/phockup.py", line 187, in get_file_name_and_path
    date = Date(filename).from_exif(exif_data, self.timestamp, self.date_regex, self.date_field)
  File "/opt/phockup/src/date.py", line 33, in from_exif
    keys = date_field.split()
TypeError: split() missing required argument 'string' (pos 1)

```

**Comment by ivandokov** [comment]
Looks like for some Python versions the `split()` [here](https://github.com/ivandokov/phockup/blob/4e0e517a4ec3ac217f4672125be491bbf780fbba/src/date.py#L33) requires an argument and for some it doesn't. This is why the tests didn't catch the issue. For example I run the tests locally on Python version 3.9.1 and I do not see the error with the code as it is. 
I replaced the way the list is created and this should be fixed.

**Comment by Yfksw65** [comment]
Hello,

Thank you the bug is fixe but now i have a new bug.

I try to run : 

`phockup  --date="YYYY/MM" --date-field="DateTimeOriginal" inputdir outputdir`

But all of file is going in unknown dir

when i made a `exiftool -time:all -mimetype -j examplepic.jpg`

i have : 

```
[{
  "SourceFile": "examplepic.jpg",
  "FileModifyDate": "2020:04:16 02:07:51+00:00",
  "FileAccessDate": "2021:02:01 19:12:38+00:00",
  "FileInodeChangeDate": "2020:04:16 02:07:51+00:00",
  "ModifyDate": "2019:12:30 20:21:36",
  "DateTimeOriginal": "2019:12:30 20:21:36",
  "MIMEType": "image/jpeg"
}]


Do you have an idea ? 

thank you 
```

**Comment by ivandokov** [comment]
@Yfksw65 are you running the latest version?
